import { CardListing, UserProfile, DealConfirmation, BulkSubmission } from "@/types";

export const MOCK_USERS: UserProfile[] = [
  {
    id: "user-1",
    username: "Levin_Mana",
    email: "levin@manaverse.gg",
    avatarUrl: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80",
    role: "founder",
    verified: true,
    dealsCount: 14,
    whatnotUsername: "ManaverseLive",
    discordUsername: "Levin#0001",
    bio: "Inhaber Manacards & Streamer auf Whatnot. Vintage & High-End Modern.",
    createdAt: "2024-01-10T12:00:00Z",
  },
  {
    id: "user-2",
    username: "PokeKarpador",
    email: "karpador@manaverse.gg",
    avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    role: "beta",
    verified: true,
    dealsCount: 5,
    whatnotUsername: "KarpadorRip",
    discordUsername: "Karpador99#1234",
    bio: "Beta-Tester & Evoli-Sammler. Immer auf der Suche nach japanischen SARs.",
    createdAt: "2024-02-01T15:30:00Z",
  },
  {
    id: "user-3",
    username: "GlurakHunter_91",
    email: "glurak@manaverse.gg",
    avatarUrl: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    role: "member",
    verified: false,
    dealsCount: 2, // 2 deals -> 1 away from verified!
    whatnotUsername: "CharizardHunter",
    discordUsername: "GlurakHunter#4567",
    bio: "Suche WOTC Holos und Base Set Gluraks in Near Mint.",
    createdAt: "2024-03-12T09:15:00Z",
  },
  {
    id: "user-4",
    username: "SnorlaxLover",
    email: "relaxo@manaverse.gg",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    role: "member",
    verified: true,
    dealsCount: 8,
    whatnotUsername: "BigSnorlax",
    discordUsername: "SleepySnorlax#8888",
    bio: "Whatnot Stammgast. Fokus auf Relaxo & Trainer Gallery.",
    createdAt: "2024-01-20T18:00:00Z",
  },
];

export const INITIAL_LISTINGS: CardListing[] = [
  {
    id: "list-1",
    userId: "user-1",
    user: MOCK_USERS[0],
    type: "sell",
    name: "Charizard / Glurak Base Set Holo",
    set: "Base Set (1999)",
    cardNumber: "4/102",
    language: "DE",
    condition: "EX",
    photos: [
      "https://images.pokemontcg.io/base1/4_hires.png",
      "https://images.pokemontcg.io/base1/4.png",
    ],
    description: "Schöne deutsche Glurak Base Set Holo Karte! Leichte Whitening Kanten auf der Rückseite, Front sauber mit tollem Holo-Schimmer. Nicht graded.",
    price: 320,
    allowOffers: true,
    postToDiscord: true,
    status: "active",
    createdAt: "2024-04-10T10:00:00Z",
  },
  {
    id: "list-2",
    userId: "user-2",
    user: MOCK_USERS[1],
    type: "sell",
    name: "Nachtara VMAX Alt Art (Moonbreon)",
    set: "Evolving Skies",
    cardNumber: "215/203",
    language: "EN",
    condition: "NM",
    photos: [
      "https://images.pokemontcg.io/swsh7/215_hires.png",
      "https://images.pokemontcg.io/swsh7/215.png",
    ],
    description: "Der heilige Gral aus Evolving Skies! Frisch aus dem Booster in Sleeve & Toploader. Perfekte Zentrierung, kein Whitening.",
    price: 850,
    allowOffers: false,
    postToDiscord: true,
    status: "active",
    createdAt: "2024-04-12T14:20:00Z",
  },
  {
    id: "list-3",
    userId: "user-1",
    user: MOCK_USERS[0],
    type: "trade",
    name: "Rayquaza VMAX Alt Art",
    set: "Evolving Skies",
    cardNumber: "218/203",
    language: "EN",
    condition: "NM",
    photos: [
      "https://images.pokemontcg.io/swsh7/218_hires.png",
    ],
    description: "Möchte mein Rayquaza VMAX Alt Art gegen Vintage WOTC Holos (Lugia Neo Genesis oder Gengar Fossil) oder gleichwertige Evoli-Evolutionen tauschen!",
    estimatedTradeValue: 420,
    lookingForWants: "Lugia Neo Genesis (NM) oder Gengar VMAX Alt Art + Ausgleich",
    allowOffers: true,
    postToDiscord: true,
    status: "active",
    createdAt: "2024-04-11T16:00:00Z",
  },
  {
    id: "list-4",
    userId: "user-3",
    user: MOCK_USERS[2],
    type: "trade",
    name: "Gengar VMAX Alt Art",
    set: "Fusion Strike",
    cardNumber: "271/264",
    language: "EN",
    condition: "NM",
    photos: [
      "https://images.pokemontcg.io/swsh8/271_hires.png",
    ],
    description: "Tausche Gengar VMAX Alt Art gegen Glurak SAR aus 151 oder Paldean Fates.",
    estimatedTradeValue: 340,
    lookingForWants: "Glurak ex 151 SIR / Charizard ex 199/165",
    allowOffers: true,
    postToDiscord: false,
    status: "active",
    createdAt: "2024-04-13T11:45:00Z",
  },
  {
    id: "list-5",
    userId: "user-4",
    user: MOCK_USERS[3],
    type: "looking_for",
    name: "Lugia 1st Edition / Neo Genesis Holo",
    set: "Neo Genesis",
    cardNumber: "9/111",
    language: "Egal",
    condition: "EX",
    photos: [
      "https://images.pokemontcg.io/neo1/9_hires.png",
    ],
    description: "Suche dringend ein Lugia aus Neo Genesis! Zustand sollte mindestens EX sein, Holo ohne tiefe Kratzer. Zahle bar oder gebe Karten in Zahlung.",
    priceRange: "250€ - 380€",
    allowOffers: true,
    postToDiscord: true,
    status: "active",
    createdAt: "2024-04-09T08:30:00Z",
  },
  {
    id: "list-6",
    userId: "user-2",
    user: MOCK_USERS[1],
    type: "looking_for",
    name: "Pikachu mit Grauer Filzhut (Van Gogh Promo)",
    set: "SVP Black Star Promos",
    cardNumber: "085",
    language: "EN",
    condition: "NM",
    photos: [
      "https://images.pokemontcg.io/base1/58_hires.png",
    ],
    description: "Suche die Van Gogh Pikachu Promo noch original sealed im Plastik! Biete fairen Marktpreis.",
    priceRange: "130€ - 160€",
    allowOffers: true,
    postToDiscord: true,
    status: "active",
    createdAt: "2024-04-14T19:00:00Z",
  },
];

export const INITIAL_DEALS: DealConfirmation[] = [
  {
    id: "deal-1",
    listingId: "hist-1",
    listingTitle: "Mewtu VSTAR Gold (Crown Zenith)",
    listingType: "sell",
    priceOrValue: 85,
    sellerId: "user-1",
    sellerUsername: "Levin_Mana",
    buyerId: "user-2",
    buyerUsername: "PokeKarpador",
    sellerConfirmed: true,
    buyerConfirmed: true,
    status: "completed",
    createdAt: "2024-03-20T10:00:00Z",
    completedAt: "2024-03-22T14:30:00Z",
  },
  {
    id: "deal-2",
    listingId: "hist-2",
    listingTitle: "Pikachu Secret Rare (Crown Zenith)",
    listingType: "trade",
    priceOrValue: 35,
    sellerId: "user-3",
    sellerUsername: "GlurakHunter_91",
    buyerId: "user-4",
    buyerUsername: "SnorlaxLover",
    sellerConfirmed: true,
    buyerConfirmed: true,
    status: "completed",
    createdAt: "2024-03-25T11:00:00Z",
    completedAt: "2024-03-28T16:00:00Z",
  },
  {
    id: "deal-3",
    listingId: "hist-3",
    listingTitle: "Gengar Trainer Gallery",
    listingType: "sell",
    priceOrValue: 18,
    sellerId: "user-3",
    sellerUsername: "GlurakHunter_91",
    buyerId: "user-1",
    buyerUsername: "Levin_Mana",
    sellerConfirmed: true,
    buyerConfirmed: true,
    status: "completed",
    createdAt: "2024-04-01T15:00:00Z",
    completedAt: "2024-04-03T09:00:00Z",
  },
];

export const INITIAL_BULK_SUBMISSIONS: BulkSubmission[] = [
  {
    id: "bulk-1",
    userId: "user-2",
    user: MOCK_USERS[1],
    totalCards: 6,
    cards: [
      {
        id: "c-1",
        name: "Glurak VMAX Shiny",
        language: "DE",
        condition: "NM",
        image: "https://images.pokemontcg.io/swsh45sv/SV107_hires.png",
        estimatedValue: 120,
      },
      {
        id: "c-2",
        name: "Roaring Moon ex SIR",
        language: "EN",
        condition: "NM",
        image: "https://images.pokemontcg.io/sv04/182_hires.png",
        estimatedValue: 75,
      },
      {
        id: "c-3",
        name: "Quajutsu ex SIR",
        language: "DE",
        condition: "NM",
        image: "https://images.pokemontcg.io/sv6pt5/64_hires.png",
        estimatedValue: 110,
      },
    ],
    askingPrice: 280,
    notes: "Komplette moderne Hits Sammlung. Alles boosterfrisch gesleevt. Schnelle Abwicklung bevorzugt!",
    status: "pending",
    createdAt: "2024-04-14T12:00:00Z",
  },
];
