import { BackgroundSlab } from "@/types/slabs";

export const BACKGROUND_SLABS_ROW_1: BackgroundSlab[] = [
  {
    id: "slab-psa-charizard",
    franchise: "pokemon",
    gradingCompany: "PSA",
    cardName: "Charizard 1st Edition Shadowless",
    setName: "1999 Pokémon Base Set",
    year: "1999",
    cardNumber: "#4/102",
    certNumber: "42918375",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/pokemon-charizard-base1.png",
    priceEst: "350.000 €",
  },
  {
    id: "slab-bgs-rayquaza",
    franchise: "pokemon",
    gradingCompany: "BGS_BLACK",
    cardName: "Rayquaza Gold Star Holo",
    setName: "2005 EX Deoxys",
    year: "2005",
    cardNumber: "#107/107",
    certNumber: "0012489601",
    grade: "10",
    gradeLabel: "BLACK LABEL",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "10",
    },
    image: "/background-slabs/pokemon-rayquaza-goldstar.png",
    priceEst: "95.000 €",
  },
  {
    id: "card-raw-pikachu-illustrator",
    franchise: "pokemon",
    gradingCompany: "RAW_MAGNETIC",
    cardName: "Pikachu Illustrator CoroCoro Promo",
    setName: "1998 Illustration Contest",
    year: "1998",
    cardNumber: "Promo",
    certNumber: "ONE-TOUCH",
    grade: "RAW",
    gradeLabel: "ONE-TOUCH UV",
    image: "/background-slabs/pokemon-pikachu-illustrator.jpg",
    priceEst: "5.000.000 €",
  },
  {
    id: "slab-cgc-umbreon",
    franchise: "pokemon",
    gradingCompany: "CGC",
    cardName: "Umbreon VMAX Moonbreon Alt Art",
    setName: "2021 SWSH Evolving Skies",
    year: "2021",
    cardNumber: "#215/203",
    certNumber: "3984125001",
    grade: "10",
    gradeLabel: "PRISTINE",
    image: "/background-slabs/pokemon-umbreon-moonbreon.png",
    priceEst: "1.450 €",
  },
  {
    id: "slab-psa-shanks",
    franchise: "one_piece",
    gradingCompany: "PSA",
    cardName: "Shanks Manga Super Parallel SEC",
    setName: "2022 OP-01 Romance Dawn",
    year: "2022",
    cardNumber: "OP01-120 SEC",
    certNumber: "68149203",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/onepiece-shanks-clean.jpg",
    priceEst: "1.900 €",
  },
];

export const BACKGROUND_SLABS_ROW_2: BackgroundSlab[] = [
  {
    id: "slab-bgs-lugia",
    franchise: "pokemon",
    gradingCompany: "BGS_BLACK",
    cardName: "Lugia 1st Edition Holo",
    setName: "2000 Neo Genesis",
    year: "2000",
    cardNumber: "#9/111",
    certNumber: "0009847120",
    grade: "10",
    gradeLabel: "BLACK LABEL",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "10",
    },
    image: "/background-slabs/pokemon-lugia-neo.png",
    priceEst: "85.000 €",
  },
  {
    id: "slab-cgc-giratina",
    franchise: "pokemon",
    gradingCompany: "CGC",
    cardName: "Giratina V Alternate Art",
    setName: "2022 SWSH Lost Origin",
    year: "2022",
    cardNumber: "#186/196",
    certNumber: "4129856003",
    grade: "10",
    gradeLabel: "PRISTINE",
    image: "/background-slabs/pokemon-giratina-alt.png",
    priceEst: "2.600 €",
  },
  {
    id: "card-raw-blastoise",
    franchise: "pokemon",
    gradingCompany: "RAW_MAGNETIC",
    cardName: "Blastoise 1st Ed. Shadowless",
    setName: "1999 Pokémon Base Set",
    year: "1999",
    cardNumber: "#2/102",
    certNumber: "ONE-TOUCH",
    grade: "RAW",
    gradeLabel: "ONE-TOUCH UV",
    image: "/background-slabs/pokemon-blastoise-base1.png",
    priceEst: "45.000 €",
  },
  {
    id: "slab-bgs-chopper",
    franchise: "one_piece",
    gradingCompany: "BGS_BLACK",
    cardName: "Tony Tony Chopper Manga Alt Art",
    setName: "2024 OP-08 Two Legends",
    year: "2024",
    cardNumber: "EB01-006 SEC",
    certNumber: "0014589201",
    grade: "10",
    gradeLabel: "BLACK LABEL",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "10",
    },
    image: "/background-slabs/onepiece-chopper-manga.jpg",
    priceEst: "1.150 €",
  },
  {
    id: "slab-psa-gengar",
    franchise: "pokemon",
    gradingCompany: "PSA",
    cardName: "Gengar VMAX Alternate Art",
    setName: "2021 SWSH Fusion Strike",
    year: "2021",
    cardNumber: "#271/264",
    certNumber: "72841659",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/pokemon-gengar-alt.png",
    priceEst: "980 €",
  },
];

export const BACKGROUND_SLABS_ROW_3: BackgroundSlab[] = [
  {
    id: "slab-bgs-latios",
    franchise: "pokemon",
    gradingCompany: "BGS_BLACK",
    cardName: "Latias & Latios GX Tag Team Alt",
    setName: "2019 SM Team Up",
    year: "2019",
    cardNumber: "#170/181",
    certNumber: "0013982451",
    grade: "10",
    gradeLabel: "BLACK LABEL",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "10",
    },
    image: "/background-slabs/pokemon-latios-latias.png",
    priceEst: "2.900 €",
  },
  {
    id: "slab-psa-charizard-151",
    franchise: "pokemon",
    gradingCompany: "PSA",
    cardName: "Charizard ex Special Art Rare",
    setName: "2023 Scarlet & Violet 151",
    year: "2023",
    cardNumber: "#199/165",
    certNumber: "90478122",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/pokemon-charizard-151.png",
    priceEst: "420 €",
  },
  {
    id: "slab-cgc-rayquaza",
    franchise: "pokemon",
    gradingCompany: "CGC",
    cardName: "Rayquaza VMAX Alternate Art",
    setName: "2021 SWSH Evolving Skies",
    year: "2021",
    cardNumber: "#218/203",
    certNumber: "4019283002",
    grade: "10",
    gradeLabel: "PRISTINE",
    image: "/background-slabs/pokemon-rayquaza-alt.png",
    priceEst: "950 €",
  },
  {
    id: "slab-bgs-mew",
    franchise: "pokemon",
    gradingCompany: "BGS_BLACK",
    cardName: "Mew Gold Star Delta Species",
    setName: "2006 EX Dragon Frontiers",
    year: "2006",
    cardNumber: "#101/101",
    certNumber: "0008745129",
    grade: "10",
    gradeLabel: "BLACK LABEL",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "10",
    },
    image: "/background-slabs/pokemon-mew-goldstar.png",
    priceEst: "12.500 €",
  },
  {
    id: "card-raw-pikachu-redcheeks",
    franchise: "pokemon",
    gradingCompany: "RAW_MAGNETIC",
    cardName: "Pikachu 1st Ed. Red Cheeks",
    setName: "1999 Pokémon Base Set",
    year: "1999",
    cardNumber: "#58/102",
    certNumber: "ONE-TOUCH",
    grade: "RAW",
    gradeLabel: "ONE-TOUCH UV",
    image: "/background-slabs/pokemon-pikachu-redcheeks.png",
    priceEst: "18.000 €",
  },
];
