import { BackgroundSlab } from "@/types/slabs";

export const BACKGROUND_SLABS_ROW_1: BackgroundSlab[] = [
  {
    id: "card-pikachu-ex-asc",
    franchise: "pokemon",
    cardName: "Pikachu ex Special Illustration Rare",
    setName: "Karmesin & Purpur: Erhabene Helden",
    year: "2024",
    cardNumber: "#276/217",
    image: "/background-slabs/pokemon-pikachu-ex-asc.jpg",
    priceEst: "420 €",
    rarity: "Special Illustration Rare",
  },
  {
    id: "card-luffy-29th-anniv",
    franchise: "one_piece",
    cardName: "Monkey D. Luffy 29th Anniversary Edition",
    setName: "Premium Card Collection 29th",
    year: "2024",
    cardNumber: "P-159",
    image: "/background-slabs/onepiece-luffy-29th-anniv.webp",
    priceEst: "650 €",
    rarity: "Premium Promo",
  },
  {
    id: "card-ahri-inquisitive",
    franchise: "riftbound",
    cardName: "Ahri, Wissbegierig (Showcase)",
    setName: "Riftbound: Wild Rift",
    year: "2025",
    cardNumber: "SP3/006",
    image: "/background-slabs/riftbound-ahri-inquisitive.jpg",
    priceEst: "890 €",
    rarity: "Showcase Champion",
  },
  {
    id: "card-mega-gengar-ex",
    franchise: "pokemon",
    cardName: "Mega Gengar ex Special Illustration Rare",
    setName: "Karmesin & Purpur: Erhabene Helden",
    year: "2024",
    cardNumber: "#284/217",
    image: "/background-slabs/pokemon-mega-gengar-ex.jpg",
    priceEst: "580 €",
    rarity: "Special Illustration Rare",
  },
  {
    id: "card-ace-st13-sp",
    franchise: "one_piece",
    cardName: "Portgas D. Ace SP Gold Foil",
    setName: "ST-13 The Three Brothers Special",
    year: "2024",
    cardNumber: "ST13-011 SR",
    image: "/background-slabs/onepiece-ace-st13-sp.jpeg",
    priceEst: "780 €",
    rarity: "Special Parallel",
  },
];

export const BACKGROUND_SLABS_ROW_2: BackgroundSlab[] = [
  {
    id: "card-lugia-v-alt",
    franchise: "pokemon",
    cardName: "Lugia V Alternate Art",
    setName: "Schwert & Schild: Silberne Sturmwinde",
    year: "2022",
    cardNumber: "#186/195",
    image: "/background-slabs/pokemon-lugia-v-alt.jpeg",
    priceEst: "220 €",
    rarity: "Alternate Art Secret Rare",
  },
  {
    id: "card-yone-blademaster",
    franchise: "riftbound",
    cardName: "Yone, Klingenmeister (Showcase Alt)",
    setName: "Riftbound: Spirit Blossom",
    year: "2025",
    cardNumber: "SFD-233/221",
    image: "/background-slabs/riftbound-yone-blademaster.jpg",
    priceEst: "950 €",
    rarity: "Showcase Signature",
  },
  {
    id: "card-ace-op02-sp",
    franchise: "one_piece",
    cardName: "Portgas D. Ace SP Alt Art",
    setName: "OP-02 Paramount War Special",
    year: "2023",
    cardNumber: "OP02-013 SR",
    image: "/background-slabs/onepiece-ace-op02-sp.png",
    priceEst: "1.250 €",
    rarity: "Special Parallel",
  },
  {
    id: "card-volibear-storm",
    franchise: "riftbound",
    cardName: "Volibear, Unbändiger Sturm (Showcase Signature)",
    setName: "Riftbound: Origins",
    year: "2025",
    cardNumber: "OGN-300/298",
    image: "/background-slabs/riftbound-volibear-storm.webp",
    priceEst: "1.100 €",
    rarity: "Showcase Signature Legend",
  },
  {
    id: "card-gengar-vmax-alt",
    franchise: "pokemon",
    cardName: "Gengar VMAX Alternate Art",
    setName: "Schwert & Schild: Fusionsangriff",
    year: "2021",
    cardNumber: "#271/264",
    image: "/background-slabs/pokemon-gengar-vmax-alt.webp",
    priceEst: "340 €",
    rarity: "Alternate Art Secret Rare",
  },
];

export const BACKGROUND_SLABS_ROW_3: BackgroundSlab[] = [
  {
    id: "card-luffy-gear5-manga",
    franchise: "one_piece",
    cardName: "Monkey D. Luffy Gear 5 Manga SEC",
    setName: "OP-05 Awakening of the New Era",
    year: "2023",
    cardNumber: "OP05-119 SEC",
    image: "/background-slabs/onepiece-luffy-gear5-manga.png",
    priceEst: "2.800 €",
    rarity: "Manga Super Parallel",
  },
  {
    id: "card-kaisa-void",
    franchise: "riftbound",
    cardName: "Kai'Sa, Tochter der Leere (Showcase Signature)",
    setName: "Riftbound: Origins",
    year: "2025",
    cardNumber: "OGN-299/298",
    image: "/background-slabs/riftbound-kaisa-void.webp",
    priceEst: "1.450 €",
    rarity: "Showcase Signature Legend",
  },
  {
    id: "card-crystal-lugia-30th",
    franchise: "pokemon",
    cardName: "Kristall-Lugia 30. Jubiläum Gold Holo",
    setName: "Pokémon 30th Anniversary Collection",
    year: "2026",
    cardNumber: "m6a #142/103",
    image: "/background-slabs/pokemon-crystal-lugia-30th.webp",
    priceEst: "3.200 €",
    rarity: "Ultra Rare Gold Border",
  },
  {
    id: "card-irelia-fervent",
    franchise: "riftbound",
    cardName: "Irelia, Leidenschaftlich (Showcase)",
    setName: "Riftbound: Spirit Blossom",
    year: "2025",
    cardNumber: "SFD-225/221",
    image: "/background-slabs/riftbound-irelia-fervent.jpeg",
    priceEst: "820 €",
    rarity: "Showcase Champion",
  },
  {
    id: "card-leona-radiant",
    franchise: "riftbound",
    cardName: "Leona, Strahlende Dämmerung (Showcase Signature)",
    setName: "Riftbound: Origins",
    year: "2025",
    cardNumber: "OGN-306/298",
    image: "/background-slabs/riftbound-leona-radiant.jpg",
    priceEst: "980 €",
    rarity: "Showcase Signature Legend",
  },
];
