import { BackgroundSlab } from "@/types/slabs";

export const BACKGROUND_SLABS_ROW_1: BackgroundSlab[] = [
  {
    id: "slab-1",
    franchise: "pokemon",
    gradingCompany: "PSA",
    cardName: "CHARIZARD - 1ST ED. SHADOWLESS",
    setName: "1999 POKÉMON BASE SET",
    year: "1999",
    cardNumber: "#4/102",
    certNumber: "41982734",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/pokemon-charizard-base1.png",
    priceEst: "350.000 €",
  },
  {
    id: "slab-2",
    franchise: "one_piece",
    gradingCompany: "BGS_BLACK",
    cardName: "MONKEY D. LUFFY (GEAR 5 MANGA)",
    setName: "2023 OP-05 AWAKENING NEW ERA",
    year: "2023",
    cardNumber: "OP05-119 SEC",
    certNumber: "0014829103",
    grade: "10",
    gradeLabel: "PRISTINE",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "10",
    },
    image: "/background-slabs/onepiece-luffy-gear5-manga.webp",
    priceEst: "4.500 €",
  },
  {
    id: "slab-3",
    franchise: "pokemon",
    gradingCompany: "PSA",
    cardName: "UMBREON VMAX (MOONBREON) ALT",
    setName: "2021 SWSH EVOLVING SKIES",
    year: "2021",
    cardNumber: "#215/203",
    certNumber: "68291044",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/pokemon-umbreon-moonbreon.png",
    priceEst: "1.200 €",
  },
  {
    id: "slab-4",
    franchise: "one_piece",
    gradingCompany: "PSA",
    cardName: "SHANKS - SUPER PARALLEL MANGA",
    setName: "2022 OP-01 ROMANCE DAWN",
    year: "2022",
    cardNumber: "OP01-120 SEC",
    certNumber: "71038291",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/onepiece-shanks-manga.webp",
    priceEst: "1.800 €",
  },
  {
    id: "slab-5",
    franchise: "pokemon",
    gradingCompany: "BGS_BLACK",
    cardName: "RAYQUAZA VMAX ALTERNATE ART",
    setName: "2021 SWSH EVOLVING SKIES",
    year: "2021",
    cardNumber: "#218/203",
    certNumber: "0015920392",
    grade: "10",
    gradeLabel: "PRISTINE",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "10",
    },
    image: "/background-slabs/pokemon-rayquaza-alt.png",
    priceEst: "3.200 €",
  },
  {
    id: "slab-6",
    franchise: "one_piece",
    gradingCompany: "CGC",
    cardName: "PORTGAS D. ACE MANGA ALT ART",
    setName: "2023 OP-02 PARAMOUNT WAR",
    year: "2023",
    cardNumber: "OP02-013 SEC",
    certNumber: "4392019001",
    grade: "10",
    gradeLabel: "PRISTINE",
    image: "/background-slabs/onepiece-ace-manga.png",
    priceEst: "1.100 €",
  },
];

export const BACKGROUND_SLABS_ROW_2: BackgroundSlab[] = [
  {
    id: "slab-7",
    franchise: "pokemon",
    gradingCompany: "BGS_BLACK",
    cardName: "GIRATINA V ALTERNATE ART",
    setName: "2022 SWSH LOST ORIGIN",
    year: "2022",
    cardNumber: "#186/196",
    certNumber: "0016729104",
    grade: "10",
    gradeLabel: "PRISTINE",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "10",
    },
    image: "/background-slabs/pokemon-giratina-alt.png",
    priceEst: "2.400 €",
  },
  {
    id: "slab-8",
    franchise: "one_piece",
    gradingCompany: "PSA",
    cardName: "RORONOA ZORO MANGA ALT ART",
    setName: "2024 OP-06 WINGS OF CAPTAIN",
    year: "2024",
    cardNumber: "OP06-118 SEC",
    certNumber: "84920193",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/onepiece-zoro-manga.webp",
    priceEst: "1.400 €",
  },
  {
    id: "slab-9",
    franchise: "pokemon",
    gradingCompany: "CGC",
    cardName: "LATIAS & LATIOS GX TAG TEAM ALT",
    setName: "2019 SM TEAM UP",
    year: "2019",
    cardNumber: "#170/181",
    certNumber: "4201938002",
    grade: "10",
    gradeLabel: "PRISTINE",
    image: "/background-slabs/pokemon-latios-latias.png",
    priceEst: "2.800 €",
  },
  {
    id: "slab-10",
    franchise: "one_piece",
    gradingCompany: "BGS_BLACK",
    cardName: "BOA HANCOCK MANGA ALT ART",
    setName: "2024 OP-07 500 YEARS FUTURE",
    year: "2024",
    cardNumber: "OP07-051 SEC",
    certNumber: "0017839201",
    grade: "10",
    gradeLabel: "PRISTINE",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "10",
    },
    image: "/background-slabs/onepiece-boa-manga.webp",
    priceEst: "3.000 €",
  },
  {
    id: "slab-11",
    franchise: "pokemon",
    gradingCompany: "PSA",
    cardName: "GENGAR VMAX ALTERNATE ART",
    setName: "2021 SWSH FUSION STRIKE",
    year: "2021",
    cardNumber: "#271/264",
    certNumber: "69103829",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/pokemon-gengar-alt.png",
    priceEst: "950 €",
  },
  {
    id: "slab-12",
    franchise: "pokemon",
    gradingCompany: "RAW_MAGNETIC",
    cardName: "PIKACHU RED CHEEKS SHADOWLESS",
    setName: "1999 BASE SET 1ST EDITION",
    year: "1999",
    cardNumber: "#58/102",
    certNumber: "RAW-001-MINT",
    grade: "RAW MINT",
    gradeLabel: "MINT GEM",
    image: "/background-slabs/pokemon-pikachu-redcheeks.png",
    priceEst: "800 €",
  },
];

export const BACKGROUND_SLABS_ROW_3: BackgroundSlab[] = [
  {
    id: "slab-13",
    franchise: "pokemon",
    gradingCompany: "BGS_GOLD",
    cardName: "LUGIA 1ST EDITION HOLO",
    setName: "2000 NEO GENESIS",
    year: "2000",
    cardNumber: "#9/111",
    certNumber: "0009281923",
    grade: "10",
    gradeLabel: "PRISTINE",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "9.5",
    },
    image: "/background-slabs/pokemon-lugia-neo.png",
    priceEst: "85.000 €",
  },
  {
    id: "slab-14",
    franchise: "one_piece",
    gradingCompany: "PSA",
    cardName: "TRAFALGAR LAW MANGA ALT ART",
    setName: "2023 OP-05 AWAKENING NEW ERA",
    year: "2023",
    cardNumber: "OP05-069 SEC",
    certNumber: "79102938",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/onepiece-law-manga.webp",
    priceEst: "900 €",
  },
  {
    id: "slab-15",
    franchise: "pokemon",
    gradingCompany: "BGS_BLACK",
    cardName: "RAYQUAZA GOLD STAR HOLO",
    setName: "2005 EX DEOXYS",
    year: "2005",
    cardNumber: "#107/107",
    certNumber: "0008392019",
    grade: "10",
    gradeLabel: "PRISTINE",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "10",
    },
    image: "/background-slabs/pokemon-rayquaza-goldstar.png",
    priceEst: "95.000 €",
  },
  {
    id: "slab-16",
    franchise: "one_piece",
    gradingCompany: "PSA",
    cardName: "SABO - SUPER PARALLEL MANGA",
    setName: "2023 OP-04 KINGDOMS INTRIGUE",
    year: "2023",
    cardNumber: "OP04-083 SEC",
    certNumber: "76509214",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/onepiece-sabo-manga.webp",
    priceEst: "850 €",
  },
  {
    id: "slab-17",
    franchise: "pokemon",
    gradingCompany: "PSA",
    cardName: "CHARIZARD EX #199 SIR",
    setName: "2023 SCARLET & VIOLET 151",
    year: "2023",
    cardNumber: "#199/165",
    certNumber: "81203948",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/pokemon-charizard-151.png",
    priceEst: "380 €",
  },
  {
    id: "slab-18",
    franchise: "one_piece",
    gradingCompany: "PSA",
    cardName: "NAMI - SPECIAL PARALLEL RARE",
    setName: "2022 OP-01 ROMANCE DAWN",
    year: "2022",
    cardNumber: "OP01-016 R",
    certNumber: "73291048",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/onepiece-nami-parallel.webp",
    priceEst: "650 €",
  },
];

export const BACKGROUND_SLABS_ROW_4: BackgroundSlab[] = [
  {
    id: "slab-19",
    franchise: "pokemon",
    gradingCompany: "PSA",
    cardName: "MEW - GOLD STAR HOLO",
    setName: "2006 EX DRAGON FRONTIERS",
    year: "2006",
    cardNumber: "#101/101",
    certNumber: "59103920",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/pokemon-mew-goldstar.png",
    priceEst: "18.000 €",
  },
  {
    id: "slab-20",
    franchise: "one_piece",
    gradingCompany: "BGS_GOLD",
    cardName: "SOGEKING MANGA ALT ART",
    setName: "2023 OP-03 PILLARS STRENGTH",
    year: "2023",
    cardNumber: "OP03-122 SEC",
    certNumber: "0013920194",
    grade: "10",
    gradeLabel: "PRISTINE",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "9.5",
    },
    image: "/background-slabs/onepiece-sogeking-manga.webp",
    priceEst: "750 €",
  },
  {
    id: "slab-21",
    franchise: "pokemon",
    gradingCompany: "CGC",
    cardName: "BLASTOISE 1ST ED. SHADOWLESS",
    setName: "1999 POKÉMON BASE SET",
    year: "1999",
    cardNumber: "#2/102",
    certNumber: "4193029104",
    grade: "10",
    gradeLabel: "PRISTINE",
    image: "/background-slabs/pokemon-blastoise-base1.png",
    priceEst: "45.000 €",
  },
  {
    id: "slab-22",
    franchise: "pokemon",
    gradingCompany: "RAW_MAGNETIC",
    cardName: "MEWTWO & MEW GX ALT ART",
    setName: "2019 SM UNIFIED MINDS",
    year: "2019",
    cardNumber: "#242/236",
    certNumber: "RAW-002-GEM",
    grade: "RAW GEM",
    gradeLabel: "MINT GEM",
    image: "/background-slabs/pokemon-mewtwo-mew.png",
    priceEst: "550 €",
  },
  {
    id: "slab-23",
    franchise: "one_piece",
    gradingCompany: "BGS_BLACK",
    cardName: "TONY TONY CHOPPER MANGA ALT",
    setName: "2024 OP-08 TWO LEGENDS",
    year: "2024",
    cardNumber: "OP08-118 SEC",
    certNumber: "0018930129",
    grade: "10",
    gradeLabel: "PRISTINE",
    subgrades: {
      centering: "10",
      corners: "10",
      edges: "10",
      surface: "10",
    },
    image: "/background-slabs/onepiece-chopper-manga.jpg",
    priceEst: "2.200 €",
  },
  {
    id: "slab-24",
    franchise: "pokemon",
    gradingCompany: "PSA",
    cardName: "PIKACHU ILLUSTRATOR HOLO",
    setName: "1998 COROCORO PROMO",
    year: "1998",
    cardNumber: "UNNUMBERED PROMO",
    certNumber: "19980001",
    grade: "10",
    gradeLabel: "GEM MT",
    image: "/background-slabs/pokemon-pikachu-illustrator.jpg",
    priceEst: "5.000.000 €",
  },
];
